language: node_js
node_js:
- "8"
before_script:
- chmod +x prebuild.sh
- ./prebuild.sh
env:
  global:
  - GH_REPO="marabesi/angular-playground"
script:
  - npm install --prefix ./todo-list
  - npm run build --prefix ./todo-list

