language: node_js
before_script:
- ./prebuild.sh
env:
  global:
  - GH_REPO="marabesi/angular-playground"
script: docpad generate
after_success:
  - test $TRAVIS_BRANCH = "master" &&
    test $TRAVIS_PULL_REQUEST = "false"
