language: node_js
node_js:
- "8"
before_script:
- chmod +x prebuild.sh
- ./prebuild.sh
env:
  global:
  - GH_REPO="marabesi/angular-playground"
script: npm install -g sync-exec --prefix && npm install -g @angular/cli && npm install --prefix ./todo-list && ng build
after_success:
  - test $TRAVIS_BRANCH = "master" &&
    test $TRAVIS_PULL_REQUEST = "false"
