language: node_js
before_script:
- chmod +x prebuild.sh
- ./prebuild.sh
env:
  global:
  - GH_REPO="marabesi/angular-playground"
script: npm install && cd todo-list && ng build
after_success:
  - test $TRAVIS_BRANCH = "master" &&
    test $TRAVIS_PULL_REQUEST = "false"
