language: node_js
node_js:
  - "10"
before_script:
  - chmod +x prebuild.sh
  - ./prebuild.sh
after_script:
  - chmod +x postbuild.sh
  - ./postbuild.sh
env:
  global:
  - GH_REPO="marabesi/angular-playground"
script:
  - npm install --prefix ./todo-list
  - npm run build --prefix ./todo-list
  - npm install --prefix ./image-preload
  - npm run build --prefix ./image-preload
  - npm install --prefix ./camera-tracking
  - npm run build --prefix ./camera-tracking
